/*
* Tailwind config
* DEPRECATED : This file is no longer used.
* It is kept here for reference only.
* The new config is in the src/styles/theme-base.css file.
* The new config is generated by the theme-plugin.
* The new config is used in the src/app/globals.css file.
*/






// /** @type {import('tailwindcss').Config} */
// import { theme as designSystemTheme } from './src/design-system/tokens/theme';
// import { colors as designSystemColors } from './src/design-system/tokens/colors';

// module.exports = {
// 	darkMode: ['class'],
// 	content: [
// 		'./pages/**/*.{ts,tsx}',
// 		'./components/**/*.{ts,tsx}',
// 		'./app/**/*.{ts,tsx}',
// 		'./src/**/*.{ts,tsx}'
// 	],
// 	theme: {
// 		container: {
// 			center: true,
// 			padding: '2rem',
// 			screens: {
// 				'2xl': '1400px',
// 			},
// 		},
	
// 		extend: {
// 			// screens: {
// 			// 	'2xl': '1200px',
// 			// 	'sm':'600px'
// 			// },
// 			...designSystemTheme.extend,
// 			colors: {
// 				...designSystemColors,
// 				primary: {
// 					...designSystemColors.primary,
// 					hello:'green' 
// 				},

// 			},
// 			borderRadius: {
// 				...designSystemTheme.borderRadius,
// 				// lg: 'var(--radius)',
// 				// md: 'calc(var(--radius) - 2px)',
// 				// sm: 'calc(var(--radius) - 4px)',
// 				// '2xl': '40px',
// 			},
// 			fontSize: {
// 				...designSystemTheme.fontSize,
// 			},
// 			fontFamily: {
// 				sans: ['var(--font-poppins)', ...designSystemTheme.fontFamily.sans],
// 				mono: [...designSystemTheme.fontFamily.mono],
// 			},
// 			keyframes: {
// 				// 'accordion-down': {
// 				// 	from: { height: 0 },
// 				// 	to: { height: 'var(--radix-accordion-content-height)' },
// 				// },
// 				// 'accordion-up': {
// 				// 	from: { height: 'var(--radix-accordion-content-height)' },
// 				// 	to: { height: 0 },
// 				// },
// 			},
// 			animation: {
// 				// 'accordion-down': 'accordion-down 0.2s ease-out',
// 				// 'accordion-up': 'accordion-up 0.2s ease-out',
// 			},
// 		},
// 	},
// 	plugins: [require('tailwindcss-animate')],
// }; 