/**
 * Programs Error Codes
 *
 * Shared error codes between backend and frontend for consistent i18n mapping
 */

export const PROGRAMS_ERROR_CODES = {
  PROGRAM_NOT_FOUND: 'PROGRAM_NOT_FOUND',
  PROGRAM_INVALID: 'PROGRAM_INVALID',
  PROGRAM_ARCHIVED: 'PROGRAM_ARCHIVED',
  MODULE_NOT_FOUND: 'MODULE_NOT_FOUND',
  MODULE_INVALID: 'MODULE_INVALID',
  LESSON_NOT_FOUND: 'LESSON_NOT_FOUND',
  LESSON_INVALID: 'LESSON_INVALID',
  ENROLLMENT_NOT_FOUND: 'ENROLLMENT_NOT_FOUND',
  ENROLLMENT_INVALID: 'ENROLLMENT_INVALID',
  ENROLLMENT_ALREADY_EXISTS: 'ENROLLMENT_ALREADY_EXISTS',
  DUPLICATE_PROGRAM: 'DUPLICATE_PROGRAM',
  INVALID_PROGRAM_DATA: 'INVALID_PROGRAM_DATA',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
} as const;

export const PROGRAMS_ERROR_CODE_TO_I18N_MAP: Record<string, string> = {
  [PROGRAMS_ERROR_CODES.PROGRAM_NOT_FOUND]: 'errors.programNotFound',
  [PROGRAMS_ERROR_CODES.PROGRAM_INVALID]: 'errors.invalidProgramData',
  [PROGRAMS_ERROR_CODES.PROGRAM_ARCHIVED]: 'errors.programArchived',
  [PROGRAMS_ERROR_CODES.MODULE_NOT_FOUND]: 'errors.programModuleNotFound',
  [PROGRAMS_ERROR_CODES.MODULE_INVALID]: 'errors.invalidProgramModule',
  [PROGRAMS_ERROR_CODES.LESSON_NOT_FOUND]: 'errors.programLessonNotFound',
  [PROGRAMS_ERROR_CODES.LESSON_INVALID]: 'errors.invalidProgramLesson',
  [PROGRAMS_ERROR_CODES.ENROLLMENT_NOT_FOUND]: 'errors.enrollmentNotFound',
  [PROGRAMS_ERROR_CODES.ENROLLMENT_INVALID]: 'errors.invalidEnrollment',
  [PROGRAMS_ERROR_CODES.ENROLLMENT_ALREADY_EXISTS]: 'errors.enrollmentAlreadyExists',
  [PROGRAMS_ERROR_CODES.DUPLICATE_PROGRAM]: 'errors.duplicateProgram',
  [PROGRAMS_ERROR_CODES.INVALID_PROGRAM_DATA]: 'errors.invalidProgramData',
  [PROGRAMS_ERROR_CODES.PERMISSION_DENIED]: 'errors.permissionDenied',
};
