/**
 * 🌐 Demo Request Error Codes - Frontend Types
 * 
 * Shared error codes between backend and frontend for consistent i18n mapping
 * These should match the error codes defined in the backend demo-request.http.ts
 */

/**
 * Demo Request Error Codes returned by the backend
 * Used for mapping to i18n translation keys
 */
export const DEMO_REQUEST_ERROR_CODES = {
  // Validation Errors (400)
  INVALID_EMAIL: 'DEMO_REQUEST_INVALID_EMAIL',
  INVALID_PHONE: 'DEMO_REQUEST_INVALID_PHONE',
  FULL_NAME_REQUIRED: 'DEMO_REQUEST_FULL_NAME_REQUIRED',
  FULL_NAME_TOO_SHORT: 'DEMO_REQUEST_FULL_NAME_TOO_SHORT',
  FULL_NAME_TOO_LONG: 'DEMO_REQUEST_FULL_NAME_TOO_LONG',
  EMAIL_REQUIRED: 'DEMO_REQUEST_EMAIL_REQUIRED',
  PHONE_REQUIRED: 'DEMO_REQUEST_PHONE_REQUIRED',

  // Business Demo Request Specific Errors
  COMPANY_NAME_REQUIRED: 'DEMO_REQUEST_COMPANY_NAME_REQUIRED',
  COMPANY_NAME_TOO_SHORT: 'DEMO_REQUEST_COMPANY_NAME_TOO_SHORT',
  COMPANY_NAME_TOO_LONG: 'DEMO_REQUEST_COMPANY_NAME_TOO_LONG',
  JOB_TITLE_REQUIRED: 'DEMO_REQUEST_JOB_TITLE_REQUIRED',
  COMPANY_SIZE_REQUIRED: 'DEMO_REQUEST_COMPANY_SIZE_REQUIRED',
  BUSINESS_TYPE_REQUIRED: 'DEMO_REQUEST_BUSINESS_TYPE_REQUIRED',

  // Coach Demo Request Specific Errors
  YEARS_OF_EXPERIENCE_REQUIRED: 'DEMO_REQUEST_YEARS_OF_EXPERIENCE_REQUIRED',
  YEARS_OF_EXPERIENCE_INVALID: 'DEMO_REQUEST_YEARS_OF_EXPERIENCE_INVALID',
  YEARS_OF_EXPERIENCE_TOO_HIGH: 'DEMO_REQUEST_YEARS_OF_EXPERIENCE_TOO_HIGH',
  AREA_OF_EXPERTISE_REQUIRED: 'DEMO_REQUEST_AREA_OF_EXPERTISE_REQUIRED',
  AREA_OF_EXPERTISE_TOO_SHORT: 'DEMO_REQUEST_AREA_OF_EXPERTISE_TOO_SHORT',
  AREA_OF_EXPERTISE_TOO_LONG: 'DEMO_REQUEST_AREA_OF_EXPERTISE_TOO_LONG',
  RESUME_FILE_REQUIRED: 'DEMO_REQUEST_RESUME_FILE_REQUIRED',
  INVALID_URL: 'DEMO_REQUEST_INVALID_URL',
  COMMENT_TOO_LONG: 'DEMO_REQUEST_COMMENT_TOO_LONG',

  // File Upload Errors
  FILE_UPLOAD_FAILED: 'DEMO_REQUEST_FILE_UPLOAD_FAILED',
  INVALID_FILE_TYPE: 'DEMO_REQUEST_INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'DEMO_REQUEST_FILE_TOO_LARGE',
  FILE_SIZE_LIMIT: 'DEMO_REQUEST_FILE_SIZE_LIMIT',

  // Conflict Errors (409)
  DUPLICATE_REQUEST: 'DEMO_REQUEST_DUPLICATE_REQUEST',
  DUPLICATE_WITH_ID: 'DEMO_REQUEST_DUPLICATE_WITH_ID',

  // Rate Limiting (429)
  RATE_LIMIT_EXCEEDED: 'DEMO_REQUEST_RATE_LIMIT_EXCEEDED',
  RATE_LIMIT_WITH_RETRY: 'DEMO_REQUEST_RATE_LIMIT_WITH_RETRY',

  // Server Errors (500)
  EMAIL_SEND_FAILED: 'DEMO_REQUEST_EMAIL_SEND_FAILED',
  PROCESSING_FAILED: 'DEMO_REQUEST_PROCESSING_FAILED',

  // Not Found Errors (404)
  DEMO_REQUEST_NOT_FOUND: 'DEMO_REQUEST_NOT_FOUND',

  // Authorization Errors (403)
  UNAUTHORIZED_ACCESS: 'DEMO_REQUEST_UNAUTHORIZED_ACCESS',

} as const;

/**
 * Demo Request Success Codes returned by the backend
 */
export const DEMO_REQUEST_SUCCESS_CODES = {
  BUSINESS_SUBMITTED: 'DEMO_REQUEST_BUSINESS_SUBMITTED',
  COACH_SUBMITTED: 'DEMO_REQUEST_COACH_SUBMITTED',
  REQUEST_UPDATED: 'DEMO_REQUEST_UPDATED',
  REQUEST_DELETED: 'DEMO_REQUEST_DELETED',
  STATUS_UPDATED: 'DEMO_REQUEST_STATUS_UPDATED',
  EMAIL_SENT: 'DEMO_REQUEST_EMAIL_SENT',
  FILE_UPLOADED: 'DEMO_REQUEST_FILE_UPLOADED',
} as const;

/**
 * Type definitions
 */
export type DemoRequestErrorCode = keyof typeof DEMO_REQUEST_ERROR_CODES;
export type DemoRequestSuccessCode = keyof typeof DEMO_REQUEST_SUCCESS_CODES;

/**
 * Error code to i18n key mapping
 * Maps backend error codes to frontend translation keys
 */
export const DEMO_REQUEST_ERROR_CODE_TO_I18N_MAP: Record<string, string> = {
  // Validation errors
  [DEMO_REQUEST_ERROR_CODES.INVALID_EMAIL]: 'errors.invalidEmail',
  [DEMO_REQUEST_ERROR_CODES.INVALID_PHONE]: 'errors.invalidPhone',
  [DEMO_REQUEST_ERROR_CODES.FULL_NAME_REQUIRED]: 'errors.fullNameRequired',
  [DEMO_REQUEST_ERROR_CODES.FULL_NAME_TOO_SHORT]: 'errors.fullNameTooShort',
  [DEMO_REQUEST_ERROR_CODES.FULL_NAME_TOO_LONG]: 'errors.fullNameTooLong',
  [DEMO_REQUEST_ERROR_CODES.EMAIL_REQUIRED]: 'errors.emailRequired',
  [DEMO_REQUEST_ERROR_CODES.PHONE_REQUIRED]: 'errors.phoneRequired',

  // Business demo request errors
  [DEMO_REQUEST_ERROR_CODES.COMPANY_NAME_REQUIRED]: 'errors.companyNameRequired',
  [DEMO_REQUEST_ERROR_CODES.COMPANY_NAME_TOO_SHORT]: 'errors.companyNameTooShort',
  [DEMO_REQUEST_ERROR_CODES.COMPANY_NAME_TOO_LONG]: 'errors.companyNameTooLong',
  [DEMO_REQUEST_ERROR_CODES.JOB_TITLE_REQUIRED]: 'errors.jobTitleRequired',
  [DEMO_REQUEST_ERROR_CODES.COMPANY_SIZE_REQUIRED]: 'errors.companySizeRequired',
  [DEMO_REQUEST_ERROR_CODES.BUSINESS_TYPE_REQUIRED]: 'errors.businessTypeRequired',

  // Coach demo request errors
  [DEMO_REQUEST_ERROR_CODES.YEARS_OF_EXPERIENCE_REQUIRED]: 'errors.yearsOfExperienceRequired',
  [DEMO_REQUEST_ERROR_CODES.YEARS_OF_EXPERIENCE_INVALID]: 'errors.yearsOfExperienceInvalid',
  [DEMO_REQUEST_ERROR_CODES.YEARS_OF_EXPERIENCE_TOO_HIGH]: 'errors.yearsOfExperienceTooHigh',
  [DEMO_REQUEST_ERROR_CODES.AREA_OF_EXPERTISE_REQUIRED]: 'errors.areaOfExpertiseRequired',
  [DEMO_REQUEST_ERROR_CODES.AREA_OF_EXPERTISE_TOO_SHORT]: 'errors.areaOfExpertiseTooShort',
  [DEMO_REQUEST_ERROR_CODES.AREA_OF_EXPERTISE_TOO_LONG]: 'errors.areaOfExpertiseTooLong',
  [DEMO_REQUEST_ERROR_CODES.RESUME_FILE_REQUIRED]: 'errors.resumeFileRequired',
  [DEMO_REQUEST_ERROR_CODES.INVALID_URL]: 'errors.invalidUrl',
  [DEMO_REQUEST_ERROR_CODES.COMMENT_TOO_LONG]: 'errors.commentTooLong',

  // File upload errors
  [DEMO_REQUEST_ERROR_CODES.FILE_UPLOAD_FAILED]: 'errors.fileUploadFailed',
  [DEMO_REQUEST_ERROR_CODES.INVALID_FILE_TYPE]: 'errors.invalidFileType',
  [DEMO_REQUEST_ERROR_CODES.FILE_TOO_LARGE]: 'errors.fileTooLarge',
  [DEMO_REQUEST_ERROR_CODES.FILE_SIZE_LIMIT]: 'errors.fileSizeLimit',

  // Conflict errors
  [DEMO_REQUEST_ERROR_CODES.DUPLICATE_REQUEST]: 'errors.duplicateRequest',
  [DEMO_REQUEST_ERROR_CODES.DUPLICATE_WITH_ID]: 'errors.duplicateRequestWithId',

  // Rate limiting
  [DEMO_REQUEST_ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'errors.rateLimitExceeded',
  [DEMO_REQUEST_ERROR_CODES.RATE_LIMIT_WITH_RETRY]: 'errors.rateLimitWithRetry',

  // Server errors
  [DEMO_REQUEST_ERROR_CODES.EMAIL_SEND_FAILED]: 'errors.emailSendFailed',
  [DEMO_REQUEST_ERROR_CODES.PROCESSING_FAILED]: 'errors.processingFailed',

  // Not found errors
  [DEMO_REQUEST_ERROR_CODES.DEMO_REQUEST_NOT_FOUND]: 'errors.demoRequestNotFound',

  // Authorization errors
  [DEMO_REQUEST_ERROR_CODES.UNAUTHORIZED_ACCESS]: 'errors.unauthorizedAccess',
};

/**
 * Success code to i18n key mapping
 */
export const DEMO_REQUEST_SUCCESS_CODE_TO_I18N_MAP: Record<string, string> = {
  [DEMO_REQUEST_SUCCESS_CODES.BUSINESS_SUBMITTED]: 'success.businessRequestSubmitted',
  [DEMO_REQUEST_SUCCESS_CODES.COACH_SUBMITTED]: 'success.coachRequestSubmitted',
  [DEMO_REQUEST_SUCCESS_CODES.REQUEST_UPDATED]: 'success.requestUpdated',
  [DEMO_REQUEST_SUCCESS_CODES.REQUEST_DELETED]: 'success.requestDeleted',
  [DEMO_REQUEST_SUCCESS_CODES.STATUS_UPDATED]: 'success.statusUpdated',
  [DEMO_REQUEST_SUCCESS_CODES.EMAIL_SENT]: 'success.emailSent',
  [DEMO_REQUEST_SUCCESS_CODES.FILE_UPLOADED]: 'success.fileUploaded',
};