/**
 * Sprints Error Codes
 *
 * Shared error codes between backend and frontend for consistent i18n mapping
 */

export const SPRINTS_ERROR_CODES = {
  SPRINT_NOT_FOUND: 'SPRINT_NOT_FOUND',
  SPRINT_INVALID: 'SPRINT_INVALID',
  SPRINT_ALREADY_STARTED: 'SPRINT_ALREADY_STARTED',
  SPRINT_ALREADY_COMPLETED: 'SPRINT_ALREADY_COMPLETED',
  SPRINT_ARCHIVED: 'SPRINT_ARCHIVED',
  GOAL_NOT_FOUND: 'GOAL_NOT_FOUND',
  GOAL_INVALID: 'GOAL_INVALID',
  DUPLICATE_SPRINT: 'DUPLICATE_SPRINT',
  INVALID_SPRINT_DATA: 'INVALID_SPRINT_DATA',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
} as const;

export const SPRINTS_ERROR_CODE_TO_I18N_MAP: Record<string, string> = {
  [SPRINTS_ERROR_CODES.SPRINT_NOT_FOUND]: 'errors.sprintNotFound',
  [SPRINTS_ERROR_CODES.SPRINT_INVALID]: 'errors.invalidSprintData',
  [SPRINTS_ERROR_CODES.SPRINT_ALREADY_STARTED]: 'errors.sprintAlreadyStarted',
  [SPRINTS_ERROR_CODES.SPRINT_ALREADY_COMPLETED]: 'errors.sprintAlreadyCompleted',
  [SPRINTS_ERROR_CODES.SPRINT_ARCHIVED]: 'errors.sprintArchived',
  [SPRINTS_ERROR_CODES.GOAL_NOT_FOUND]: 'errors.sprintGoalNotFound',
  [SPRINTS_ERROR_CODES.GOAL_INVALID]: 'errors.invalidSprintGoal',
  [SPRINTS_ERROR_CODES.DUPLICATE_SPRINT]: 'errors.duplicateSprint',
  [SPRINTS_ERROR_CODES.INVALID_SPRINT_DATA]: 'errors.invalidSprintData',
  [SPRINTS_ERROR_CODES.INVALID_DATE_RANGE]: 'errors.invalidDateRange',
  [SPRINTS_ERROR_CODES.PERMISSION_DENIED]: 'errors.permissionDenied',
};
