/**
 * Audit Error Codes
 *
 * Shared error codes between backend and frontend for consistent i18n mapping
 */

export const AUDIT_ERROR_CODES = {
  AUDIT_LOG_NOT_FOUND: 'AUDIT_LOG_NOT_FOUND',
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
  INVALID_FILTERS: 'INVALID_FILTERS',
  EXPORT_FAILED: 'EXPORT_FAILED',
  ANALYTICS_DATA_UNAVAILABLE: 'ANALYTICS_DATA_UNAVAILABLE',
  ANOMALY_DETECTION_FAILED: 'ANOMALY_DETECTION_FAILED',
  PATTERN_ANALYSIS_FAILED: 'PATTERN_ANALYSIS_FAILED',
  DASHBOARD_DATA_FAILED: 'DASHBOARD_DATA_FAILED',
} as const;

export const AUDIT_ERROR_CODE_TO_I18N_MAP: Record<string, string> = {
  [AUDIT_ERROR_CODES.AUDIT_LOG_NOT_FOUND]: 'errors.auditLogNotFound',
  [AUDIT_ERROR_CODES.REPORT_NOT_FOUND]: 'errors.reportNotFound',
  [AUDIT_ERROR_CODES.INVALID_DATE_RANGE]: 'errors.invalidDateRange',
  [AUDIT_ERROR_CODES.INVALID_FILTERS]: 'errors.invalidFilters',
  [AUDIT_ERROR_CODES.EXPORT_FAILED]: 'errors.exportFailed',
  [AUDIT_ERROR_CODES.ANALYTICS_DATA_UNAVAILABLE]: 'errors.analyticsDataUnavailable',
  [AUDIT_ERROR_CODES.ANOMALY_DETECTION_FAILED]: 'errors.anomalyDetectionFailed',
  [AUDIT_ERROR_CODES.PATTERN_ANALYSIS_FAILED]: 'errors.patternAnalysisFailed',
  [AUDIT_ERROR_CODES.DASHBOARD_DATA_FAILED]: 'errors.dashboardDataFailed',
};
