// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from the translations in the 'dictionary' directory

export interface Translations {
  common: {
    config: CommonConfigTranslations;
    demoRequest: CommonDemoRequestTranslations;
    metadata: CommonMetadataTranslations;
    auth: CommonAuthTranslations;
    footer: CommonFooterTranslations;
    navbar: CommonNavbarTranslations;
  };
  components: {
    footer: ComponentsFooterTranslations;
  };
  pages: {
    dashboard: PagesDashboardTranslations;
    demo: PagesDemoTranslations;
    index: PagesIndexTranslations;
  };
}

export interface CommonConfigTranslations {
  settings: string;
  theme: string;
  light: string;
  dark: string;
  language: string;
  HELP: string;
  NEWARAB: string;
  FROMARAB: string;
  FROMENGLISH: string;
  FROMFRENCH: string;
}

export interface CommonDemoRequestTranslations {
  errors: CommonDemoRequestTranslationsErrors;
  success: CommonDemoRequestTranslationsSuccess;
  suggestions: CommonDemoRequestTranslationsSuggestions;
}

export interface CommonDemoRequestTranslationsErrors {
  network: string;
  server: string;
  unauthorized: string;
  forbidden: string;
  validationFailed: string;
  unexpected: string;
  invalidEmail: string;
  invalidPhone: string;
  fullNameRequired: string;
  fullNameTooShort: string;
  fullNameTooLong: string;
  emailRequired: string;
  phoneRequired: string;
  companyNameRequired: string;
  companyNameTooShort: string;
  companyNameTooLong: string;
  jobTitleRequired: string;
  companySizeRequired: string;
  businessTypeRequired: string;
  yearsOfExperienceRequired: string;
  yearsOfExperienceInvalid: string;
  yearsOfExperienceTooHigh: string;
  areaOfExpertiseRequired: string;
  areaOfExpertiseTooShort: string;
  areaOfExpertiseTooLong: string;
  resumeFileRequired: string;
  invalidUrl: string;
  commentTooLong: string;
  fileUploadFailed: string;
  invalidFileType: string;
  fileTooLarge: string;
  fileSizeLimit: string;
  duplicateRequest: string;
  duplicateRequestWithId: string;
  rateLimitExceeded: string;
  rateLimitWithRetry: string;
  emailSendFailed: string;
  processingFailed: string;
  demoRequestNotFound: string;
  unauthorizedAccess: string;
}

export interface CommonDemoRequestTranslationsSuccess {
  businessRequestSubmitted: string;
  coachRequestSubmitted: string;
  requestUpdated: string;
  requestDeleted: string;
  statusUpdated: string;
  emailSent: string;
  fileUploaded: string;
}

export interface CommonDemoRequestTranslationsSuggestions {
  duplicateRequest: string;
  rateLimitExceeded: string;
  invalidPhone: string;
  fileUploadFailed: string;
  fileTooLarge: string;
  invalidFileType: string;
  emailSendFailed: string;
}

export interface CommonMetadataTranslations {
  title: string;
  description: string;
  keywords: string;
  something: string;
}

export interface CommonAuthTranslations {
  login: CommonAuthTranslationsLogin;
  forgotPassword: CommonAuthTranslationsForgotPassword;
  register: CommonAuthTranslationsRegister;
  resetPassword: CommonAuthTranslationsResetPassword;
  checkEmail: CommonAuthTranslationsCheckEmail;
  errors: CommonAuthTranslationsErrors;
  success: CommonAuthTranslationsSuccess;
}

export interface CommonAuthTranslationsLogin {
  title: string;
  subtitle: string;
  emailLabel: string;
  passwordLabel: string;
  rememberMe: string;
  loginButton: string;
  loginButtonLoading: string;
  forgotPassword: string;
  errors: CommonAuthTranslationsLoginErrors;
}

export interface CommonAuthTranslationsLoginErrors {
  invalidCredentials: string;
  networkError: string;
  serverError: string;
  required: string;
}

export interface CommonAuthTranslationsForgotPassword {
  title: string;
  subtitle: string;
  emailLabel: string;
  sendButton: string;
  backToLogin: string;
}

export interface CommonAuthTranslationsRegister {
  title: string;
  subtitle: string;
  firstNameLabel: string;
  lastNameLabel: string;
  emailLabel: string;
  passwordLabel: string;
  confirmPasswordLabel: string;
  registerButton: string;
  alreadyHaveAccount: string;
  loginLink: string;
}

export interface CommonAuthTranslationsResetPassword {
  title: string;
  subtitle: string;
  passwordLabel: string;
  confirmPasswordLabel: string;
  updateButton: string;
  updateButtonLoading: string;
  backToLogin: string;
}

export interface CommonAuthTranslationsCheckEmail {
  title: string;
  subtitle: string;
  resendButton: string;
  resendButtonLoading: string;
  resendButtonCooldown: string;
  countdownMessage: string;
  successTitle: string;
  successSubtitle: string;
  backToLogin: string;
}

export interface CommonAuthTranslationsErrors {
  network: string;
  server: string;
  unauthorized: string;
  forbidden: string;
  notFound: string;
  tooManyRequests: string;
  invalidCredentials: string;
  invalidToken: string;
  tokenExpired: string;
  passwordsDoNotMatch: string;
  passwordTooShort: string;
  passwordTooLong: string;
  invalidEmail: string;
  emailRequired: string;
  passwordRequired: string;
  noActiveResetRequest: string;
  rateLimitExceeded: string;
  userNotFound: string;
  accountLocked: string;
  emailNotVerified: string;
  twoFactorRequired: string;
  invalidTwoFactorCode: string;
  sessionExpired: string;
  unexpected: string;
}

export interface CommonAuthTranslationsSuccess {
  passwordResetSent: string;
  passwordResetSuccess: string;
  passwordChanged: string;
  emailVerified: string;
  loginSuccess: string;
}

export interface CommonFooterTranslations {
  links: CommonFooterTranslationsLinks;
  copyright: string;
  contact: CommonFooterTranslationsContact;
  social: CommonFooterTranslationsSocial;
}

export interface CommonFooterTranslationsLinks {
  termsAndConditions: string;
  accessibility: string;
  privacyPolicy: string;
}

export interface CommonFooterTranslationsContact {
  phoneAlt: string;
  whatsappAlt: string;
  emailAlt: string;
  locationAlt: string;
}

export interface CommonFooterTranslationsSocial {
  linkedinAlt: string;
  facebookAlt: string;
  instagramAlt: string;
  youtubeAlt: string;
  tiktokAlt: string;
}

export interface CommonNavbarTranslations {
  bookDemo: string;
  login: string;
  logoAlt: string;
}

export interface ComponentsFooterTranslations {
  copyright: string;
  copyright2: string;
  githubLink: string;
  copyrightWithBreak: string;
}

export interface PagesDashboardTranslations {
  metadata: PagesDashboardTranslationsMetadata;
  navigation: PagesDashboardTranslationsNavigation;
}

export interface PagesDashboardTranslationsMetadata {
  title: string;
  description: string;
}

export interface PagesDashboardTranslationsNavigation {
  profile: string;
  teams: string;
  requests: string;
  themes: string;
}

export interface PagesDemoTranslations {
  roleSelector: PagesDemoTranslationsRoleSelector;
}

export interface PagesDemoTranslationsRoleSelector {
  title: string;
  subtitle: string;
  coach: PagesDemoTranslationsRoleSelectorCoach;
  business: PagesDemoTranslationsRoleSelectorBusiness;
}

export interface PagesDemoTranslationsRoleSelectorCoach {
  title: string;
  description: string;
  cta: string;
}

export interface PagesDemoTranslationsRoleSelectorBusiness {
  title: string;
  description: string;
  cta: string;
}

export interface PagesIndexTranslations {
  boilerplateName: string;
  title: string;
  description: string;
  cloneRepository: string;
  leaveStar: string;
  cnUtilsExamples: string;
  howToUse: string;
  gettingStarted: string;
  installation: string;
  howToContribute: string;
  omitrtlUsage: string;
  OmitRTLInstruction: string;
  contribute: string;
  installationSteps: PagesIndexTranslationsInstallationSteps;
  contributeSteps: PagesIndexTranslationsContributeSteps;
  error: PagesIndexTranslationsError;
}

export interface PagesIndexTranslationsInstallationSteps {
  cloneRepository: string;
  installDependencies: string;
  startDevServer: string;
}

export interface PagesIndexTranslationsContributeSteps {
  fork: string;
  createBranch: string;
  commit: string;
  push: string;
  pullRequest: string;
}

export interface PagesIndexTranslationsError {
  server: string;
  sorry: string;
  tryAgain: string;
  returnHome: string;
}

// Type for translation namespaces
export type TranslationNamespace = 
  | "common.config"
  | "common.demoRequest"
  | "common.metadata"
  | "common.auth"
  | "common.footer"
  | "common.navbar"
  | "components.footer"
  | "pages.dashboard"
  | "pages.demo"
  | "pages.index";
