/**
 * Upload Error Codes
 *
 * Shared error codes between backend and frontend for consistent i18n mapping
 */

export const UPLOAD_ERROR_CODES = {
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  CHUNKED_UPLOAD_NOT_FOUND: 'CHUNKED_UPLOAD_NOT_FOUND',
  CHUNKED_UPLOAD_INVALID: 'CHUNKED_UPLOAD_INVALID',
  CHUNK_NOT_FOUND: 'CHUNK_NOT_FOUND',
  CHUNK_ALREADY_UPLOADED: 'CHUNK_ALREADY_UPLOADED',
  UPLOAD_INCOMPLETE: 'UPLOAD_INCOMPLETE',
  INVALID_CHUNK_SIZE: 'INVALID_CHUNK_SIZE',
  STORAGE_QUOTA_EXCEEDED: 'STORAGE_QUOTA_EXCEEDED',
} as const;

export const UPLOAD_ERROR_CODE_TO_I18N_MAP: Record<string, string> = {
  [UPLOAD_ERROR_CODES.FILE_NOT_FOUND]: 'errors.fileNotFound',
  [UPLOAD_ERROR_CODES.FILE_UPLOAD_FAILED]: 'errors.fileUploadFailed',
  [UPLOAD_ERROR_CODES.FILE_TOO_LARGE]: 'errors.fileTooLarge',
  [UPLOAD_ERROR_CODES.INVALID_FILE_TYPE]: 'errors.invalidFileType',
  [UPLOAD_ERROR_CODES.CHUNKED_UPLOAD_NOT_FOUND]: 'errors.chunkedUploadNotFound',
  [UPLOAD_ERROR_CODES.CHUNKED_UPLOAD_INVALID]: 'errors.invalidChunkedUpload',
  [UPLOAD_ERROR_CODES.CHUNK_NOT_FOUND]: 'errors.chunkNotFound',
  [UPLOAD_ERROR_CODES.CHUNK_ALREADY_UPLOADED]: 'errors.chunkAlreadyUploaded',
  [UPLOAD_ERROR_CODES.UPLOAD_INCOMPLETE]: 'errors.uploadIncomplete',
  [UPLOAD_ERROR_CODES.INVALID_CHUNK_SIZE]: 'errors.invalidChunkSize',
  [UPLOAD_ERROR_CODES.STORAGE_QUOTA_EXCEEDED]: 'errors.storageQuotaExceeded',
};
