/**
 * Scheduling Error Codes
 *
 * Shared error codes between backend and frontend for consistent i18n mapping
 */

export const SCHEDULING_ERROR_CODES = {
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_INVALID: 'SESSION_INVALID',
  SESSION_CONFLICT: 'SESSION_CONFLICT',
  UNAVAILABLE_TIME: 'UNAVAILABLE_TIME',
  SESSION_ALREADY_COMPLETED: 'SESSION_ALREADY_COMPLETED',
  SESSION_ALREADY_STARTED: 'SESSION_ALREADY_STARTED',
  SESSION_ALREADY_CANCELLED: 'SESSION_ALREADY_CANCELLED',
  CANNOT_RESCHEDULE: 'CANNOT_RESCHEDULE',
  CANNOT_CANCEL: 'CANNOT_CANCEL',
  REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
  REQUEST_ALREADY_ACCEPTED: 'REQUEST_ALREADY_ACCEPTED',
  REQUEST_ALREADY_REJECTED: 'REQUEST_ALREADY_REJECTED',
  COACH_UNAVAILABLE: 'COACH_UNAVAILABLE',
  COACH_NOT_FOUND: 'COACH_NOT_FOUND',
  INVALID_TIME_RANGE: 'INVALID_TIME_RANGE',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
} as const;

/**
 * Error code to i18n key mapping
 */
export const SCHEDULING_ERROR_CODE_TO_I18N_MAP: Record<string, string> = {
  [SCHEDULING_ERROR_CODES.SESSION_NOT_FOUND]: 'errors.sessionNotFound',
  [SCHEDULING_ERROR_CODES.SESSION_INVALID]: 'errors.invalidSessionData',
  [SCHEDULING_ERROR_CODES.SESSION_CONFLICT]: 'errors.sessionConflict',
  [SCHEDULING_ERROR_CODES.UNAVAILABLE_TIME]: 'errors.unavailableTime',
  [SCHEDULING_ERROR_CODES.SESSION_ALREADY_COMPLETED]: 'errors.sessionAlreadyCompleted',
  [SCHEDULING_ERROR_CODES.SESSION_ALREADY_STARTED]: 'errors.sessionAlreadyStarted',
  [SCHEDULING_ERROR_CODES.SESSION_ALREADY_CANCELLED]: 'errors.sessionAlreadyCancelled',
  [SCHEDULING_ERROR_CODES.CANNOT_RESCHEDULE]: 'errors.cannotRescheduleSession',
  [SCHEDULING_ERROR_CODES.CANNOT_CANCEL]: 'errors.cannotCancelSession',
  [SCHEDULING_ERROR_CODES.REQUEST_NOT_FOUND]: 'errors.requestNotFound',
  [SCHEDULING_ERROR_CODES.REQUEST_ALREADY_ACCEPTED]: 'errors.requestAlreadyAccepted',
  [SCHEDULING_ERROR_CODES.REQUEST_ALREADY_REJECTED]: 'errors.requestAlreadyRejected',
  [SCHEDULING_ERROR_CODES.COACH_UNAVAILABLE]: 'errors.coachUnavailable',
  [SCHEDULING_ERROR_CODES.COACH_NOT_FOUND]: 'errors.coachNotFound',
  [SCHEDULING_ERROR_CODES.INVALID_TIME_RANGE]: 'errors.invalidTimeRange',
  [SCHEDULING_ERROR_CODES.INVALID_DATE_RANGE]: 'errors.invalidDateRange',
};
